FROM node:24-slim

WORKDIR /app

# Copy root configurations
COPY package*.json ./
# Copy workspace configurations
COPY frontend/package*.json ./frontend/

# Install dependencies (workspaces support)
RUN npm ci --include=optional

# Copy source code for frontend (can be overridden by volumes)
COPY frontend ./frontend

EXPOSE 5173

# Start development server configured to accept connections from outside the container
CMD ["npm", "run", "dev", "-w", "frontend", "--", "--host"]
