FROM node:22-slim

WORKDIR /app

ENV NPM_CONFIG_OMIT=

# Copy root configurations
COPY package*.json ./
# Copy workspace configurations
COPY frontend/package*.json ./frontend/

# Install dependencies (workspaces support)
RUN npm ci --include=optional --no-audit --no-fund

# Copy source code for frontend (can be overridden by volumes)
COPY frontend ./frontend

EXPOSE 5173

# Start development server configured to accept connections from outside the container
CMD ["npm", "run", "dev", "-w", "frontend", "--", "--host"]
