FROM node:24-slim
WORKDIR /app

COPY package*.json ./
COPY frontend/package*.json ./frontend/

RUN npm ci --no-audit --no-fund

COPY frontend ./frontend

EXPOSE 5173

CMD ["npm", "run", "dev", "-w", "frontend", "--", "--host"]
