#!/usr/bin/env sh

# Run tests
echo "Running Frontend Tests..."
npx vitest run --root frontend || exit 1

echo "Running Backend Tests..."
npx vitest run --root backend || exit 1

echo "Running Go Service Tests..."
go test -C ext-api-service -v ./... || exit 1
