#!/usr/bin/env sh

npx lint-staged

# Enforce signed commits
if [ "$(git config --get commit.gpgsign)" != "true" ]; then
  echo "Error: automatic commit signing is required for this repository."
  echo "Please enable commit signing by running: git config commit.gpgsign true"
  exit 1
fi

# tests are not working yet
# npm test
