#!/usr/bin/env sh

# Run tests
echo "Running Frontend Tests..."
npm test --prefix frontend --if-present || exit 1

echo "Running Backend Tests..."
npm test --prefix backend --if-present || exit 1

echo "Running Go Service Tests..."
go test -C ext-api-service -v ./... || exit 1
